{
 "title": "Beagle Board Data",
 "time": { "from": "2019-05-20T09:30:00.000Z", "to": "2019-05-20T09:32:00.000Z" },
 "panels": [
  {
   "title": "Accelerometer - Raw Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "accelerometer",
     "select": [
      [
       { "params": [ "acc_x" ], "type": "field" }
      ],
      [
       { "params": [ "acc_y" ], "type": "field" }
      ],
      [
       { "params": [ "acc_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accelerometer - PCA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "PCA",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ],
      [
       { "params": [ "anomaly" ], "type": "field" }
      ],
      [
       { "params": [ "threshold" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accelerometer - Autoencoder",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "autoencoder",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" }
      ],
      [
       { "params": [ "distance" ], "type": "field" }
      ],
      [
       { "params": [ "threshold" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}